 CREATE TABLE IF NOT EXISTS LA_ORPHANED_LOG_EVENTS(ID varchar(20), HOST varchar(20), STATE VARCHAR(20),TYPE VARCHAR(40),TIMESTAMP BIGINT);
 
 CREATE TABLE IF NOT EXISTS LA_LOG_EVENT_ALERTS(ID varchar(20), HOST varchar(20), TYPE VARCHAR(40),EVENT_DURATION INTEGER,ALERT boolean);